window.BaseMainState = {
  version: '0.0.0.0.0.0.0.1',
  storage: {
    theme: 'base-main-theme',
    hand: 'base-main-hand'
  },
  themes: [
    'Ciano',
    'Cianeto',
    'Claro',
    'Escuro',
    'Cinza',
    'AreiaSolar',
    'AbismoSolar',
    'RoxoTotal',
    'Agilidade',
    'Ambar',
    'Ameixa',
    'Arco',
    'Atlantico',
    'Azulejo',
    'Beastie',
    'BigPinguim',
    'BrotoEscuro',
    'Cacau',
    'CampoAzul',
    'ChamaRoxa',
    'Compacto',
    'Concreto',
    'Expressivo',
    'GeloNoturno',
    'Jardim',
    'MalhaLivre',
    'Mica',
    'Mosaico',
    'MuralhaRubra',
    'Nebulosa',
    'OitoBits',
    'PapelCinza',
    'Pergaminho',
    'Permissao',
    'RetroClaro',
    'TerminalVerde',
    'Turquesa',
    'Vidro',
    'Violeta'
  ]
};
